### ISSUE TITLE
Display issue in flanca (from The world to reverse)

### ISSUE THREAD

**Issue by nafnlj** [Galladite27/ONScripter-EN#3]
## Game description

flanca is one of two novels which make up The World to Reverse.

Downloads: https://apothes.is/hosted/at2006/theworldtoreverse.html

## My environment

I ran these tests on my desktop workstation which uses EndeavourOS. For Windows, I used the original  executable provided with the al|together 2006 release and ran it with WINE. For Linux, I am using the newest ONScripter-EN release (6.28.23) from this repository. I tested ONScripter-EN 2011 and the version prior to proportional fonts support and had the same experience, so it is not unique to the releases in this repository. The 2006 Linux executable does not run on my system.

## Issue

flanca is an entirely text-based novel. It has many choices with two options. In the original Windows version, the choices appear under the preceding text:

![flanca-windows](https://github.com/Galladite27/ONScripter-EN/assets/77352335/b338cea0-be46-41fc-a8e4-d3e9e5a4e47d)

However, when running it natively on Linux, the preceding text disappears and only the choice is visible:

![flanca-linux-ons62823](https://github.com/Galladite27/ONScripter-EN/assets/77352335/62b47afb-d3bf-420b-a62a-0992046eedf9)

The novel functions in both cases, but I am confident from context that the correct behavior is what I see in the Windows version with WINE.

## Other notes

Link to the original customized ONScripter that was used for the 2006 release: https://altogether.b-cdn.net/at2006/at2006/twtr_onscripter.tar.bz2

See MIDI sound issue for the first novel in The world to reverse, hallucinate: #2

**Comment by Galladite27** [comment]
I'll look into this one shortly. Thanks for reporting.

**Comment by Galladite27** [comment]
The issue is with the "selectbtnwait" command. When it's called, other text seems to be hidden, only to be redrawn afterwards. Looking into why now.

**Comment by Galladite27** [comment]
I've found that "selectbtnwait" didn't have a rule implemented that it shouldn't hide the text display window like other button selects may do. This has now been fixed, unless GP32 or Chaos Kaiser give a reason why this behaviour should be as it is.

The reason I think this is incorrect behaviour is that the normal "select" command doesn't hide the text display window, and since "selectbtnwait" is one command used in modifying the "select" command, it should act the same unless specified otherwise in the script.
