### ISSUE TITLE
Linking error on OpenBSD

### ISSUE THREAD

**Issue by grodzio1** [Galladite27/ONScripter-EN#37]
Compiling on OpenBSD (clang) fails due to a linking error, caused by `ONScripterLabel_command.cpp` and `ONScripterLabel_command.o`. Attached in ```log.txt``` is the full compiler output. Also attached is a patch that I used to bypass the error.
[log.txt](https://github.com/Galladite27/ONScripter-EN/files/15192089/log.txt)
[patch_ONScripterLabel_command_cpp.txt](https://github.com/Galladite27/ONScripter-EN/files/15192090/patch_ONScripterLabel_command_cpp.txt)

**Comment by Galladite27** [comment]
From Discord:
"Because it tries to do a hacky fix for linux, not realising it's BSD
IIRC the actual problem isn't the fix, but that it tries to use the fix here without including the file during compilation on OpenBSD"

I think `#if defined(LINUX)` returns positive on OpenBSD, but in the configure script they are treated as separate and the necessary file is only included on linux, not OpenBSD.

**Comment by SeanMcG** [comment]
Fixed by #39
