### ISSUE TITLE
FreeType2 extlib never marks itself as completed

### ISSUE THREAD

**Issue by SeanMcG** [Galladite27/ONScripter-EN#6]
Something is not quite right with the `make`-ish in the generated `Makefile` or `Makefile.extlibs`.

WIth current `master` branch, repeatedly calling `make` spews the following even if the internal FreeType was built successfully:

```
$ make
Building internal Freetype...
```

**Comment by Galladite27** [comment]
The instructions for building Freetype (Makefile.extlibs L236) have one issue I can see that needs fixing, but I'm not sure that it's related to this issue.

The target is "$(EB)/freetype-config" (/extlib/bin/freetype-config) which would have made sense originally but now doesn't. It checks for if the file "extlib/bin/freetype-config" is created, but when I was updating the libraries I ran into a bug where it wasn't being put there after compilation. I made a quick fix where I use a hand-written freetype-config, which works just about (may be buggy but it's only temporary), but I really should fix it properly at some point.

Not only is the file not put there any more, but the generated freetype-config (for linux in "/extlib/src/freetype-2.13.0/builds/unix/freetype-config")  thinks that the prefix is /usr, so clearly it's not being generated properly now, since L234 of Makefile.extlibs clearly specifies the prefix to Freetype.

Though this is an issue I'll have to fix, I don't know if it's related to this; what I'd assume is happening is that the target $(FTCONFIGURE) is appearing to change and so causing it to be done every time, but I don't know why that'd be.
